name: Exchange Rate CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r 'requirements.txt'

      - name: Run tests
        run: |

          export PYTHONPATH="${PYTHONPATH}:$(pwd)"
          pytest tests/ -v

      - name: Run SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey='JakRec_WSB_20230514' \
            -Dsonar.organization='jakrec' \
            -Dsonar.sources='app/' \
            -Dsonar.tests='tests/' \
            -Dsonar.python.coverage.reportPaths=coverage.xml \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN
